### ISSUE TITLE
dimmable devices turn off but not on

### ISSUE THREAD

**Issue by respectTheCode** [rodtoll/homebridge-isy-js#3]
Dimmable devices can dim and turn off but when an app or Siri turns the device on the dim % doesn't change and the device doesn't turn on.

**Comment by rodtoll** [comment]
Could you provide a set of repro steps. I have dimmable lights in my house and can test.

Are you saying that if you:
1. Dim a light.
2. Turn it off.
3. Turn it on and it doesn't turn on? 

If so, which steps were siri based and which were done manually.

With detailed steps I can reproduce and fix it.

**Comment by respectTheCode** [comment]
Siri and several HomeKit apps seem to do the same thing. I have tested with Insteon+, iDevices and the HMCatalog example app. All 3 apps behave the same way.

| Starting Status | Off | Dim | On |
| --- | --- | --- | --- |
| 0% | N/A | Yes | No |
| 50% | Yes | Yes* | No |
| 100% | Yes | Yes* | N/A |
- Dimming lags and the dim status jumps up and down for a while

**Comment by rodtoll** [comment]
@respectTheCode - Re: Stuttering. In Insteon+ and a few other applications dimming is handled very poorly and inefficiently. Essentially when you slide the slider from 0 to 100 it sends 100 dim commands. Dim level 1, dim level 2, dim level 3, etc. all the way to Dim 100. The homebridge server and the underlying plugins get backed up and I suspect because of race conditions end up arriving and being executed on out of order (hence the stuttering and the jumping around). The only fix I can see is to break the dim scale into subsets .. i.e. 0-10, 11-20, etc. and then ignore commands that are for the same range. This will cause a bunch of commands to be ignored as redundant which should speed things up -- but I believe you still may see some stuttering. 

My favorite HomeKit application currently is Home - Smart Home Automation. It only sends the dim command when you release the slider so it sends only one command. Unfortunately it is $14.99US but it has been by far the most reliable and easy to use of the apps.

Working to repro the not turn on issue now. Wanted to let you know about the stuttering issue.

**Comment by respectTheCode** [comment]
That makes sense. The simplest solution for that type of problem is typically to debounce the calls.

https://lodash.com/docs#debounce

**Comment by respectTheCode** [comment]
So I started digging into this a little more and I found the problem. `http://{ip}/rest/nodes/{address}/cmd/DON` does not work anymore. You need to set an on value like ``http://{ip}/rest/nodes/{address}/cmd/DON/255`. I think I read that this is fixed in one of the 5.x betas.

**Comment by PaulWieland** [comment]
@respectTheCode is this issue then tied to the ISY firmware revision? I can't say that I've encountered this problem with mine. `"Siri turn the ______  off"` works just fine.

**Comment by respectTheCode** [comment]
I just updated my ISY to 5.0.2 and it is working correctly. So it must be an issue 4.3.x (not sure what version I was on before).
