### ISSUE TITLE
Instead Lights don't turn off

### ISSUE THREAD

**Issue by ghost** [rodtoll/homebridge-isy-js#32]
I can turn on the insteon lights, but the off command doesn't work. Any ideas?

**Comment by ghost** [comment]
here is the log event.  I see the true event occur...nothing happens on the false (off) command

 116-8-0#12:21:36- OUTLET: Game Room Fan Sending command to set outlet state to: true
2016-8-0#12:21:36- ISY-JS: Sending command...http://192.168.1.46/rest/nodes/13 F5 4D 1/cmd/DON

[9/18/2016, 12:21:45 PM] [isy-js] 116-8-0#12:21:45- OUTLET: Game Room Fan Sending command to set outlet state to: false

**Comment by ghost** [comment]
Also, using isy99i on 3.3.10 firmware

**Comment by rodtoll** [comment]
This issue is commonly caused by 1 of 2 issues:
1. You have an outdated ISY firmware. 
   Update to the latest will address this.
2. You have too many pieces of software talking to the ISY at once. 
   The ISY can only handle about 6 clients for notifications and ISY needs one of them to work. When the notifications are not working then the symptom is you can change the status of the device once but never again. So for example if they are off when you startup you can turn them on but then won't be able to turn them off. Only fix here is to reduce the number of pieces of software talking to ISY.

I have not found any other root causes for this issue to date.

**Comment by rodtoll** [comment]
Didn't intend to close issue. Apologies.

**Comment by rodtoll** [comment]
Going to close. The instances of this are tracked back to folks using ISY 99i. That device is end of life and it has issues with websocket notifications which this library depends on. Will add notes to README.
